server:
  port: 8088
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: kitri1234
    key-password: kitri1234
    key-alias: spring

spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/weatherwear?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1234
  messages:
    basename: messages

logging:
  level:
    ROOT: INFO